stock = {
    # raw material
    'coal': 0,
    'copper_ore': 0,
    'deuterium': 0,
    'fire_ice': 0,
    'hydrogen': 0,
    'iron_ore': 0,
    'organic_crystal': 0,
    'silicon_ore': 0,
    'spiniform_stalagmite_crystal': 0,
    'stone': 0,
    'sulfuric_acid': 0,
    'titanium_ore': 0,
    'water': 0,

    # parts
    'carbon_nanotube': 0,
    'casimir_crystal': 0,
    'circuit_board': 0,
    'copper_ingot': 0,
    'deuteron_fuel_rod': 0,
    'dyson_sphere_component': 0,
    'electric_motor': 0,
    'electromagnetic_turbine': 0,
    'energetic_graphite': 0,
    'frame_material': 0,
    'gear': 0,
    'glass': 0,
    'graphene': 0,
    'high-purity_silicon': 0,
    'iron_ingot': 0,
    'magnet': 0,
    'magnetic_coil': 0,
    'microcrystalline_component': 0,
    'photon_combiner': 0,
    'plane_filter': 0,
    'prism': 0,
    'processor': 0,
    'quantum_chip': 0,
    'small_carrier_rocket': 0,
    'solar_sail': 0,
    'steel': 0,
    'super-magnetic_ring': 0,
    'titanium_alloy': 0,
    'titanium_crystal': 0,
    'titanium_glass': 0,
    'titanium_ingot': 0,

    # no use
    'NULL': 0,
}
